server:
  podAnnotations:
    reloader.stakater.com/auto: "true"
    config-reload-timestamp: "{{ now | quote }}"

  resources:
    limits:
      cpu: 200m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 128Mi
  retentionPeriod: 48h

  # Extra arguments for the VM server
  extraArgs:
    search.maxPointsPerTimeseries: "86400"  # Limit points per series
    search.maxQueryDuration: "30s"  # Limit long-running queries

  # Configure persistent storage
  persistentVolume:
    enabled: true
    size: 1Gi
    mountPath: /storage

  # Enable and configure scraping
  scrape:
    enabled: true
    config:
      global:
        scrape_interval: 60s
      scrape_configs:
        # Frontend application scraping
        - job_name: frontend
          metrics_path: /api/metrics
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - toffolon-website-staging
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              regex: staging-toffolon-front
              action: keep

        # Backend application scraping
        - job_name: backend
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              regex: staging-toffolon-backend
              action: keep
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              regex: metrics
              action: keep

        # Node metrics scraping (similar to node exporter)
        - job_name: node-metrics
          bearer_token: ""
          scheme: https
          kubernetes_sd_configs:
            - role: node
          tls_config:
            insecure_skip_verify: true
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [ __meta_kubernetes_node_name ]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/${1}/proxy/metrics

  # Configure service
  service:
    servicePort: 8428
    targetPort: http
    type: ClusterIP

serviceAccount:
  create: true
  name: victoria-metrics-victoria-metrics-single-server


