---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: "{{ .Values.appName }}-container"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            limits:
              memory: "728Mi"  # Maximum memory allowed
              cpu: "600m"       # Maximum CPU allowed (500 milliCPU)
            requests:
              memory: "348Mi"  # Initial memory request
              cpu: "300m" # Initial CPU request
          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: backend-secret
      initContainers:
        - name: init-db-dir
          image: busybox
          command: [ "sh", "-c", "mkdir -p /mnt/data/prisma && chmod -R 777 /mnt/data/prisma" ]
          volumeMounts:
            - mountPath: /mnt/data/prisma
              name: prisma-storage