---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prisma-pv
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  capacity:
    storage: {{.Values.persistentVolume.capacity.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}