apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prisma-pvc
  labels:
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.capacity.storage }}
  storageClassName: standard