apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prisma-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.capacity.storage }}
  storageClassName: standard