apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
data:
  SEND_GRID_KEY: ${SEND_GRID_KEY_BASE64}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_BACKEND_BASE64}
  AWS_ACCESS_KEY_SECRET: ${AWS_ACCESS_KEY_SECRET_BACKEND_BASE64}
  FIRST_EMAIL_USER: ${FIRST_EMAIL_USER_BASE64}
