apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
data:
  SEND_GRID_KEY: {{ .Values.secrets.data.SEND_GRID_KEY }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.data.AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY_SECRET: {{ .Values.secrets.data.AWS_ACCESS_KEY_SECRET }}
  FIRST_EMAIL_USER: {{ .Values.secrets.data.FIRST_EMAIL_USER }}
