version: '3'
services:
  back:
    build:
      context: backend
      dockerfile: dockerfile
    ports:
      - "3002:3002"
  front:
    build:
      context: front
      dockerfile: dockerfile
    ports:
      - "3000:3000"
