# Build Stage

FROM node:21-alpine

WORKDIR /app

RUN chown node:node /app

USER node

COPY package.json ./

RUN yarn install

COPY --chown=node:node . /app

COPY --chown=node:node src/prisma ./prisma

RUN npx prisma generate

RUN yarn build

ENTRYPOINT ["yarn"]

CMD ["start:prod"]
