FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NODE_ENV=development
RUN corepack enable
COPY . /app
WORKDIR /app

FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base AS build
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
COPY . .
COPY /src/prisma ./prisma
RUN pnpm prisma generate
RUN pnpm run build

FROM base
ENV DATABASE_URL="file:./../dev.db"
ENV PORT=8000
ENV NODE_ENV=production
# Copy built application
COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/src/prisma ./prisma
COPY --from=build /app/node_modules/.pnpm/@prisma+client@4.16.2_prisma@4.16.2/node_modules/.prisma ./node_modules/.prisma
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
EXPOSE 8000
CMD [ "pnpm", "start:migrate:prod" ]