---
- name: Enable helm adds-on
  shell: sudo /snap/bin/microk8s enable helm

- name: Add bitnami repository
  shell: sudo /snap/bin/microk8s helm repo add bitnami https://charts.bitnami.com/bitnami

- name: Update repository
  shell: sudo /snap/bin/microk8s helm repo update

- name: Copy redis-value.yaml
  template:
    src: templates/redis-values.yaml.j2
    dest: /tmp/redis-values.yaml
    mode: '0644'

- name: Install redis
  shell: sudo /snap/bin/microk8s helm upgrade --install my-redis bitnami/redis -f /tmp/redis-values.yaml -n {{ deployment_namespace }}