---
- name: Update APT package cache
  become: yes
  apt:
    update_cache: yes

- name: Upgrade all APT packages
  become: yes
  apt:
    upgrade: dist
    autoremove: yes

- name: Install required packages
  apt:
    name:
      - snapd
      - curl
      - gnupg2
    state: present

- name: Ensure snapd is up to date (required for microk8s/core20)
  become: yes
  command: sudo snap install core snapd

- name: Install MicroK8s via snap manually
  become: yes
  command: sudo snap install microk8s --classic --channel={{ microk8s_channel }}

- name: Add user to microk8s
  user:
    name: ansible
    groups: microk8s
    append: yes
  register: user_add

- name: Allow microk8s group to access .kube directory
  file:
    path: ~/.kube
    state: directory
    mode: '0755'
  when: user_add.changed

- name: Wait for microk8s to be ready
  shell: /snap/bin/microk8s status --wait-ready
  changed_when: false
  timeout: 30000

- name: Enable required add-ons
  shell: "/snap/bin/microk8s enable {{ item }}"
  loop: "{{ enable_addons }}"
  changed_when: true

- name: Copy namespace config
  template:
    src: templates/namespace.yaml
    dest: /tmp/namespace.yaml
    mode: '0644'

- name: Install namespace
  shell: /snap/bin/microk8s kubectl apply -f /tmp/namespace.yaml

- name: Copy role config
  template:
    src: templates/role.yaml
    dest: /tmp/role.yaml
    mode: '0644'

- name: Install role
  shell: /snap/bin/microk8s kubectl apply -f /tmp/role.yaml

- name: Copy service account config
  template:
    src: templates/service-account.yaml
    dest: /tmp/service-account.yaml
    mode: '0644'

- name: Install service account
  shell: /snap/bin/microk8s kubectl apply -f /tmp/service-account.yaml

- name: Copy role biding config
  template:
    src: templates/role-biding.yaml
    dest: /tmp/role-biding.yaml
    mode: '0644'

- name: Install role biding
  shell: /snap/bin/microk8s kubectl apply -f /tmp/role-biding.yaml

- name: Copy role cluster config
  template:
    src: templates/role-cluster.yaml
    dest: /tmp/role-cluster.yaml
    mode: '0644'

- name: Install role biding
  shell: /snap/bin/microk8s kubectl apply -f /tmp/role-cluster.yaml

- name: Copy role biding cluster
  template:
    src: templates/role-biding-cluster.yaml
    dest: /tmp/role-biding-cluster.yaml
    mode: '0644'

- name: Install role biding
  shell: /snap/bin/microk8s kubectl apply -f /tmp/role-biding-cluster.yaml

- name: Get Kubernetes config
  shell: /snap/bin/microk8s config
  register: kube_config

- name: Copy service account generator config
  template:
    src: templates/generate-sa-config.sh
    dest: /tmp/generate-sa-config.sh
    mode: '0755'

- name: Setup config file for service account
  shell: /tmp/generate-sa-config.sh
  register: sa_config_output

- name: Install cert-manager
  shell: sudo /snap/bin/microk8s kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.0/cert-manager.yaml

- name: Fetch the generated kubeconfig
  fetch:
    src: ./sa-kubeconfig.yaml
    dest: /tmp/
    flat: yes

- name: Remove temporary script
  file:
    path: /tmp/generate-sa-config.sh
    state: absent
  when: cleanup_temp_files | default(true)
