---
- name: Setup microk8s playbook
  hosts: all
  remote_user: ansible
  become: yes
  roles:
    - microk8s

  vars:
    microk8s_channel: 1.32
    enable_addons:
      - dns
      - dashboard
      - storage
      - ingress
      - metrics-server
      - rbac