# Default values for helm-front-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: staging-toffolon-front
namespace: toffolon # To be updated along with ansible for enable environment namespace

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  host: staging.toffolon-peinture-deco.fr
  tls:
    - secretName: nginx-tls
      hosts:
        - staging.toffolon-peinture-deco.fr

configMap:
  data:
    API_HOST: "https://staging.toffolon-peinture-deco.fr/api"