name: Build and push front image

on:
  push:
    tags:
      - 'front-v*.*.*'
  workflow_dispatch:
    inputs:
      test-tag:
        description: 'Tag to test image creation'

env:
  REGISTRY: ghcr.io

jobs:
  call-build-push:
    uses: ./.github/workflows/build-and-push-docker-image.yaml
    with:
      image-name: toffolon-front
      context-path: ./front
      dockerfile-path: ./front/dockerfile
      test-tag: ${{ github.event.inputs.test-tag }}
    secrets: inherit